# Generated by Django 5.0.6 on 2024-06-02 05:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255)),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
