# Generated by Django 5.0.6 on 2024-06-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_text_ticket_content_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(),
        ),
    ]
