# Generated by Django 5.0.6 on 2024-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='susick', max_length=255, unique=True, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
